name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main", "feature/github-actions" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-13
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          xcodebuild clean build analyze -scheme Empusa | xcpretty && exit ${PIPESTATUS[0]}
